{% set name = "mypy_boto3_builder" %}
{% set version = "7.23.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d3248c416baeec6c228a5dbc41a78f4223a35fae27531a4dab346fc25b8263d9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.10,<4.0
    - poetry-core
  run:
    # From pyproject.toml, [tool.poetry.dependencies]
    - typing_extensions *
    - python >=3.10.0,<4.0.0
    - pip *
    - boto3 *
    - black *
    - isort *
    - jinja2 *
    - mdformat *
    - newversion *
    - cryptography *

test:
  imports:
    - mypy_boto3_builder
    - mypy_boto3_builder.enums
  commands:
    - pip check
    # Test fails on Windows with permission denied:
    - python -m mypy_boto3_builder mypy_boto3_output
  requires:
    - pip

about:
  home: https://pypi.org/project/mypy-boto3-builder/
  summary: Builder for boto3-stubs
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
    - thewchan
    - vemel
