{% set name = "mypy_boto3_builder" %}
{% set version = "8.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 498479db0ecb3828ca4efafb57af15a8ebfbae75c40835cb6aae8bade5341d10

build:
  entry_points:
    - mypy_boto3_builder = mypy_boto3_builder.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python >=3.12
    - setuptools
  run:
    - python >=3.12
    - boto3
    - jinja2
    - mdformat
    - packaging
    - requests
    - ruff
    - setuptools

test:
  imports:
    - mypy_boto3_builder
  commands:
    - pip check
    - mypy_boto3_builder --help
  requires:
    - pip

about:
  home: https://pypi.org/project/mypy-boto3-builder/
  summary: Builder for boto3-stubs and types-aiobotocore
  license: MIT
  license_file:
    - LICENSE
    - mypy_boto3_builder/templates/common/LICENSE.jinja2

extra:
  recipe-maintainers:
    - maresb
    - thewchan
    - vemel
