{% set name = "mypy_boto3_builder" %}
{% set version = "8.6.1" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 86c8a7255b1ebc04247187df5255deb4bf3730939c8e826cdfc64d367928f4b1

build:
  entry_points:
    - mypy_boto3_builder = mypy_boto3_builder.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - botocore
    - colorama
    - prompt-toolkit
    - questionary >=2.0.1
    - python >={{ python_min }}
    - boto3
    - jinja2
    - mdformat
    - packaging
    - requests
    - ruff
    - setuptools

test:
  imports:
    - mypy_boto3_builder
  commands:
    - pip check
    - mypy_boto3_builder --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/youtype/mypy_boto3_builder
  summary: Builder for boto3-stubs and types-aiobotocore
  license: MIT
  license_file:
    - LICENSE
    - mypy_boto3_builder/templates/common/LICENSE.jinja2

extra:
  recipe-maintainers:
    - maresb
    - thewchan
    - vemel
