{% set name = "mypy_boto3_builder" %}
{% set version = "4.18.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mypy-boto3-builder-{{ version }}.tar.gz
  sha256: 1c9bcc07a56362955fa78f85174aa12f8fd5af2f791afdcda4abdb7ab8d9a05d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8,<4.0
    - poetry-core
  run:
    # From pyproject.toml, [tool.poetry.dependencies]
    - black >=21.4b2
    - boto3
    - isort >=5.6.4,<6.0.0
    - jinja2 >=3.0.1,<4.0.0
    - md-toc >=7.2.0  # Older versions of md-toc seem to lead to inconsistent requirements.
    - mdformat
    - pyparsing
    - pip
    - python >=3.8,<4.0

test:
  imports:
    - mypy_boto3_builder
    - mypy_boto3_builder.enums
  commands:
    - pip check
    # Test fails on Windows with permission denied:
    - python -m mypy_boto3_builder mypy_boto3_output
  requires:
    - pip

about:
  home: https://pypi.org/project/mypy-boto3-builder/
  summary: Builder for boto3-stubs
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
    - thewchan
    - vemel
