{% set name = "mypy_boto3_builder" %}
{% set version = "7.5.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mypy-boto3-builder-{{ version }}.tar.gz
  sha256: 34a71bd7dbb70f234331d8ab60e585ea153f06c056c2ccad735443eaa9fc8115

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.10,<4.0
    - poetry-core
  run:
    # From pyproject.toml, [tool.poetry.dependencies]
    - python >=3.10,<4.0
    - pip
    - boto3
    - black >=22.1.0,<23
    - isort >=5.10.0,<6.0.0
    - jinja2 >=3.0.1,<4.0.0
    - pyparsing >=3.0.5,<4.0.0
    - mdformat >=0.7.9,<0.8.0
    - newversion >=1.8.2,<2.0.0
    - requests >=2.26.0,<3.0.0

test:
  imports:
    - mypy_boto3_builder
    - mypy_boto3_builder.enums
  commands:
    - pip check
    # Test fails on Windows with permission denied:
    - python -m mypy_boto3_builder mypy_boto3_output
  requires:
    - pip

about:
  home: https://pypi.org/project/mypy-boto3-builder/
  summary: Builder for boto3-stubs
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
    - thewchan
    - vemel
