{% set name = "mypy_boto3_builder" %}
{% set version = "8.9.0" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a75bfe4769b5ee4c0188ef1aa4b3a5eef2be2eeaa5eefef0cff52a0e48b8d471

build:
  entry_points:
    - mypy_boto3_builder = mypy_boto3_builder.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - loguru
    - boto3
    - prompt-toolkit
    - python >={{ python_min }}
    - jinja2
    - mdformat
    - packaging
    - botocore
    - requests
    - ruff
    - setuptools
    - colorama
    - questionary >=2.0.1

    # questionary 2.0.1 has requirement prompt_toolkit<=3.0.36,>=2.0
    - prompt_toolkit <=3.0.36,>=2.0

test:
  imports:
    - mypy_boto3_builder
  commands:
    - pip check
    - mypy_boto3_builder --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/youtype/mypy_boto3_builder
  summary: Builder for boto3-stubs and types-aiobotocore
  license: MIT
  license_file:
    - LICENSE
    - mypy_boto3_builder/templates/common/LICENSE.jinja2

extra:
  recipe-maintainers:
    - maresb
    - thewchan
    - vemel
